---
- hosts: all
  sudo: true
  tasks:
    - name: update apt cache
      apt: update_cache=yes
    - name: install nodejs
      apt: name=nodejs state=present
    - name: install npm
      apt: name=npm state=present
    - name: Install npm packages from packages.json
      npm: path=/vagrant/
