---
- hosts: all
  sudo: true
  tasks:
    - name: update apt cache
      apt: update_cache=yes
    - name: install nodejs
      apt: name=nodejs state=latest
    - name: install npm
      apt: name=npm state=latest
    - name: Install npm packages from packages.json
      npm: path=/vagrant/
    - name: Install tmux
      apt: name=tmux state=latest
    - name: copy tmux conf
      copy: src=/vagrant/provisioning/.tmux.conf dest=/home/vagrant/.tmux.conf owner=vagrant group=foo mode=0644
